### ISSUE TITLE
Last host ignored if the file does not have a line break at the end.

### ISSUE THREAD

**Issue by smed79** [funilrys/funceble#171]
Hi,

without a line break at the end of the file, the last host is ignored.

- http://i.imgur.com/cbLm2yw.png
- http://i.imgur.com/MZLzvMY.png

**Is this a normal behavior?**

Thank you.

**Comment by funilrys** [comment]
Hi, 
Let me first thank you for feedback and support :+1: 

Can you give me the output of `./funceble -v` ? :)

**Comment by funilrys** [comment]
This is what I tried so far  ...

![master](https://user-images.githubusercontent.com/14127285/30602704-b072bd7e-9d65-11e7-85c7-f518e6dcf6ee.png)

![dev](https://user-images.githubusercontent.com/14127285/30602720-bd63ae12-9d65-11e7-93c5-684dc73db616.png)

**Comment by smed79** [comment]
> Can you give me the output of ./funceble -v ?

`Current Version: 1.4.0`

- http://i.imgur.com/jI5zeX9.png (Not an outdated version...)

**Comment by funilrys** [comment]
>  (Not an outdated version...)

@SMed79 You could also use the dev version or one of the other released version :wink: 

It's really strange as it's not an **excepted behavior** ... :thinking:

**Comment by funilrys** [comment]
What is your bash version? 

Mine:
```bash
$ bash --version
bash --version
GNU bash, version 4.4.12(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by funilrys** [comment]
Can I get your file(s)? :smile_cat:

**Comment by SMed79** [comment]
Using the dev version, I had the **same** behavior !!
Later, I will try on a second computer /OS.

![funilrys](http://i.imgur.com/L6u2I4x.png)

**Comment by smed79** [comment]
Using the dev version, I had the **same** behavior !!
Later, I will try on a second computer /OS.

![funilrys](http://i.imgur.com/L6u2I4x.png)

**//EDIT:**

> What is your bash version?

```
$ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
Licence GPLv3+ : GNU GPL version 3 ou ultérieure <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

> Can I get your file(s)?

[hosts.zip](https://github.com/funilrys/funceble/files/1315078/hosts.zip)

**Comment by funilrys** [comment]
@SMed79 Are you sure it's the right file ? 

```bash
$ cat -e extra/issues/171/hosts 
github.com$
```

**Comment by mitchellkrogza** [comment]
Just good  practice to have an empty line at the end of all your input lists. I work with some major lists which combine inputs from 20+ sources, every input source ends with an empty line and for good reason. Take 20 lists make half of them end with an empty line and make he other half NOT end on an empty line. Now combine those lists into one and see what mess shall endure. 

I'll give you an example

One list ends with

Domain.com (and no empty line after it)

Next list ends with

Domain2.com (plus empty line below it)

Now when combining lists you can easily end up with this 

Domain1.comDomain2.com

**Comment by mitchellkrogza** [comment]
A very good and trusted git desktop app Sourcetree actually gives you warnings when committing plain text files "no newline at end of file"

**Comment by funilrys** [comment]
About that issue, after some search, I'm not gonna change anything now but it's a known behavior (just discovered that) when using the following.

```bash
while read lineToRead
do
    # ${lineToRead} manipulation
done < ${fileToRead}
```
-----------------------------------------------------------------------------------

To quote this [answer/question](https://stackoverflow.com/a/12916758/5308363) : 
> The C standard says that text files must end with a newline or the data after the last newline may not be read properly.
**ISO/IEC 9899:2011 §7.21.2 Streams**
A text stream is an ordered sequence of characters composed into lines, each line consisting of zero or more characters plus a **terminating new-line character**.

**Comment by smed79** [comment]
> Just good practice to have an empty line at the end of all your input lists.

I do that all the time. It's just that I discovered this issue by coincidence and I wanted to know what's wrong.

Thanks for your time.
