### ISSUE TITLE
Improve regex on --filter function (blogspot)

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/funceble#176]
Regex seems to be finding any domain with the word blogspot in it, see below.

![screen shot 2017-09-26 at 1 03 40 pm](https://user-images.githubusercontent.com/9961541/30857235-451788a6-a2bb-11e7-8ad2-1c6416d9e3ec.png)

**Comment by funilrys** [comment]
Hum that's not really an issue @mitchellkrogza :joy_cat: 

- `./funceble --filter .blogspot. -f MyAwesomeHosts`  ==> Test all `*.blogspot.*`
-  `./funceble --filter \.blogspot\. -f MyAwesomeHosts`  ==> Test all `*.blogspot.*`
-  `./funceble --filter blogspot -f MyAwesomeHosts`  ==> Test all `*blogspot*`

**Comment by mitchellkrogza** [comment]
Thanks @funilrys I missed somewhere about feeding it regex like that 👍
