### ISSUE TITLE
Add -t timeout option?

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/funceble#46]
Might be nice to have a -t parameter switch to set the timeout in seconds. Default timeout appears to be 1 minutes would be nice to set it to 20-30 seconds to speed up checking of lists.

**Comment by funilrys** [comment]
Timeout is coming @mitchellkrogza  :wink:  just finished to write it once I tested and documented it you gonna have it in the next release :smile_cat: 

It's should also fix #44 

Thanks for feedback,
Thanks for actively using this script/repo !
