### ISSUE TITLE
Error with temporary file

### ISSUE THREAD

**Issue by funilrys** [funilrys/funceble#58]
Report of @mitchellkrogza issue

> When running it now with latest version I get this error.
>
> ```
> ./funceble: line 322: expect: command not found
> cat: /var/tmp/whois.32129: No such file or directory
> ```

**Comment by funilrys** [comment]
Strange @mitchellkrogza I don't have such issue is it on your ubuntu server? 

I know where does this issue came from (I had this one during development) so gonna find a workaround

**Comment by mitchellkrogza** [comment]
@funilrys yes on Ubuntu 16.04

**Comment by funilrys** [comment]
Okay gonna test there !

**Comment by funilrys** [comment]
What was your timeout value @mitchellkrogza ?

**Comment by mitchellkrogza** [comment]
I ran it with both the following and got the same error.

`./funceble -a -t 15 -h -f domains.txt`

and

`./funceble -a -h -f domains.txt`

**Comment by funilrys** [comment]
Thanks @mitchellkrogza :) 
Did you installed `apt-get install expect` ? (forgot to add it to dependencies :sob: )

Gonna publish a fix once I tested your commands :wink:

**Comment by mitchellkrogza** [comment]
`apt-get install expect` fixed that 👍  checks running much faster now with `-t 15` 👍

**Comment by mitchellkrogza** [comment]
I launched a new project here - https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites now I want to try and integrate funceble into the Travis CI build process to check for and delete dead domains but I'll do that at a later date.

**Comment by mitchellkrogza** [comment]
@funilrys your new -t timeout option is a God send. Thank you !!!! So much quicker now to check big lists. Ran it against my latest list from https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/_generator_lists/bad-referrers.list containing 5268 entries and it's been running for just over an hour and already at "t" so nearly done. Previously this would take a few hours to check. 👍  💯

**Comment by mitchellkrogza** [comment]
Took about 90 minutes to run through that list of 5268 entries and not a bad output. Seems my lists are still nice and clean and functional.

```
Status      Percentage   Numbers
----------- ------------ -------------
ACTIVE      98%          5250
INACTIVE    1%           55
INVALID     0%           0
```

**Comment by funilrys** [comment]
Awesome @mitchellkrogza  !!!  
I noticed it too when testing with you list !!! Thanks again :+1: :100: 

Your list is almost always nice and clean since I discovered it :stuck_out_tongue_winking_eye: 


>  I want to try and integrate funceble into the Travis CI build process to check for and delete dead domains but I'll do that at a later date.

Interesting idea. Can't wait to see your work !! :smile_cat:

**Comment by mitchellkrogza** [comment]
Will let you know when I have figured it out 😀  going to take some careful scripting to get Travis CI to play along with this idea
