### ISSUE TITLE
[GUI] Possible feature for funceble?

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/funceble#62]
@funilrys been wondering how difficult it would be to make funceble produce an HTML page showing active domains, expiry date and a screen shot of the front page of the site? Would be a cool way to look through lists of domains and see the screen shot of the page, would help with identifying previously bad domains that perhaps are now no longer bad. For instance abc.xyz used to be a spam domain but now is owned by Google Alhabet.

**Comment by funilrys** [comment]
Interesting ! Gonna take a look at it :)

**Comment by mitchellkrogza** [comment]
Found this which may be one solution to try this out - https://github.com/sindresorhus/pageres-cli

**Comment by funilrys** [comment]
Also found https://wkhtmltopdf.org/downloads.html :)

**Comment by mitchellkrogza** [comment]
Lots of options, going to check this one out in the morning too

**Comment by funilrys** [comment]
If I implement it 5000 pictures will be a lot @mitchellkrogza that'll be the next problem :joy_cat:

**Comment by mitchellkrogza** [comment]
Oh hell yeah, would be interesting to see on a test repo how big the repo gets just on one list

**Comment by mitchellkrogza** [comment]
@funilrys As mentioned in another thread perhaps doing a simple curl to get the page title of a page would help people sort and clean their lists. This could be include in results.txt or even separate files??? So pages that return a name other than 404 or not found go into one result file and ones that return a page name other than 404, missing or not found go into a separate file. This way, especially with lists that have subdomains of a root domain like blogspot.com etc it would be easy to pick up blogs that no longer exist.

**Comment by funilrys** [comment]
Can you please create a new issue about it so we can track it @mitchellkrogza :+1: ?

Was out with family so I'm back to my keyboard :stuck_out_tongue_winking_eye:

**Comment by funilrys** [comment]
@mitchellkrogza : 
> I suggested a feature or even a totally new project which can run funceble against these lists and produce a screenshot of each site in a nice PDF or HTML output which could help people seeing what sites are dead or still active.
