### ISSUE TITLE
Change the percentage log file name

### ISSUE THREAD

**Issue by funilrys** [funilrys/funceble#64]
As @mitchellkrogza  reported [here](https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/pull/1#issuecomment-316406256) it may be better to rename the percentage log file name to `percentage.txt`

**Comment by mitchellkrogza** [comment]
I fixed it for now on my Travis build by just adding `sudo cp $TRAVIS_BUILD_DIR/.dev-tools/_funceble/output/logs/percentage/_* $TRAVIS_BUILD_DIR/.dev-tools/_funceble/percentage.txt`
