### ISSUE TITLE
Add update procedure somewhere

### ISSUE THREAD

**Issue by xxcriticxx** [funilrys/funceble#69]
@funilrys i hope am not asking for to much on my first day here but can i please get wiki on how to update to newest version.

**Comment by funilrys** [comment]
No problem @xxcriticxx 

I didn't write it yet but It's gonna be documented for new release (coming today or tomorrow in Berlin Time)

**Comment by xxcriticxx** [comment]
thank you pleasure working with you

**Comment by funilrys** [comment]
Gonna be updated as soon as 1.3.2 become deprecated but you can now find the procedure [there](https://github.com/funilrys/funceble/wiki/Update)

Closing.
