### ISSUE TITLE
clean file

### ISSUE THREAD

**Issue by xxcriticxx** [funilrys/funceble#70]
can you get script to create clean file with inactive removed? useful for big host list

**Comment by xxcriticxx** [comment]
nvm it does this already in the host folder

**Comment by funilrys** [comment]
I don't understand your issue @xxcriticxx ... 

Isn't that what you have under https://github.com/funilrys/dead-hosts/tree/master/pl-host-file/ACTIVE ?

**Comment by xxcriticxx** [comment]
you can close this i already answer my own question
