### ISSUE TITLE
Expiration Date 

### ISSUE THREAD

**Issue by xxcriticxx** [funilrys/funceble#72]
why is my expiration date always unknown?

**Comment by funilrys** [comment]
What is the command you used to test your list/domain ?

**Comment by xxcriticxx** [comment]
./funceble -f list location

**Comment by funilrys** [comment]
What is the output of `./funceble -v` ? 

If you get unknown it's because we can't read the output of `whois` as said in the [Status Wiki](https://github.com/funilrys/funceble/wiki/Status).

**Comment by xxcriticxx** [comment]
i don't have access to that computer right now but its the newest one i updated yesterday

**Comment by funilrys** [comment]
If you are the only user, please check your `umask`

**Comment by funilrys** [comment]
@xxcriticxx any feedback? :)

**Comment by funilrys** [comment]
No feedback after +24h.

Closing.
