### ISSUE TITLE
check for sudo

### ISSUE THREAD

**Issue by xxcriticxx** [funilrys/funceble#73]
should you check for sudo/root before installation?

**Comment by funilrys** [comment]
No need for sudo @xxcriticxx.

**Comment by xxcriticxx** [comment]
just asking because i have to do everything with sudo because i get lots permission denied messages i guess we can close this

**Comment by funilrys** [comment]
That's impossible unless you don't have permission to access the current directory ...

@mitchellkrogza Did you noticed such things cause I personally not ...

**Comment by mitchellkrogza** [comment]
I'm always logged into my servers as root anyway so not sure if sudo is needed or not. I always log in with `sudo -s` 

Inside Travis I execute my funceble with `sudo bash $TRAVIS_BUILD_DIR/.dev-tools/install-run-funceble.sh` so inside Travis sudo is required.

**Comment by funilrys** [comment]
Okay, thanks. I personally use Linux over 3 computers and have no problem without root. 
You have to check your permissions @xxcriticxx.

Closing.
