### ISSUE TITLE
How important is the "Analyse Date" column for you ?

### ISSUE THREAD

**Issue by funilrys** [funilrys/funceble#82]
As I'm working on a big change in the way data are shown on screen and *ONLY* on screen, I wanted to know your opinion.

cc @mitchellkrogza @xxcriticxx and others that use funceble :smile_cat:

**Comment by mitchellkrogza** [comment]
On screen not important for me at all. In the results.txt file absolutely 💯 % important for me.

**Comment by xxcriticxx** [comment]
if you drop on screen will you gain any speed?

**Comment by funilrys** [comment]
@xxcriticxx we already have a quiet option (Please report to --help), it's a really bit faster but not that much.

**Comment by mitchellkrogza** [comment]
@xxcriticxx quite possible actually. One of my new repo's when run in Debug mode on Travis which outputs everything to screen ran for over 50 minutes and the build died. The moment I turned off debugging, the script executed and completed the build in 2 and a half minutes. @funilrys would turning off screen display actually speed up funceble ???

**Comment by funilrys** [comment]
@mitchellkrogza Avoid debug mode with that 1million line :rofl: The debug mode activates the output of everything from whois output to formated logs :rofl: Sorry I should write it somewhere :+1:

**Comment by funilrys** [comment]
As long as you don't activate debug mode, quiet mode should be faster from 5 to 15 seconds 

You're pointing something interesting @mitchellkrogza :rocket: :+1: :+1: 

We should deactivate the debug mode for dead-hosts (where did my mind goes ? :thinking:) ...

**Comment by mitchellkrogza** [comment]
🤣  mind .... what's that 🤣  .... I lost mine years ago 🤣 🤣 🤣 

But yeah, let's see how much faster it runs with debug OFF

**Comment by funilrys** [comment]
I just realized that I lost my mind when I restarted dead-hosts :rofl::rofl::rofl::rofl::rofl::rofl::rofl::rofl: 

Let's see ==> https://travis-ci.org/funilrys/dead-hosts/builds/257628468

**Comment by mitchellkrogza** [comment]
🤣 🤣 🤣  ..... busy watching that build now

**Comment by mitchellkrogza** [comment]
Wonder if there will be any speed increase in Travis on this build https://travis-ci.org/funilrys/dead-hosts/builds/257628468 with screen output of funceble turned off?

**Comment by funilrys** [comment]
Let's test when it's done with your list :+1:

**Comment by mitchellkrogza** [comment]
Seems to make no difference running funceble in quiet mode.

https://travis-ci.org/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/builds

**Comment by funilrys** [comment]
@mitchellkrogza 
From 37 to 34 minutes ===> https://travis-ci.org/funilrys/dead-hosts/builds/257647593

With:
https://github.com/funilrys/dead-hosts/blob/master/Badd-Boyz-Hosts/tool#L248

**Comment by mitchellkrogza** [comment]
😮  that is certainly some improvement.

**Comment by funilrys** [comment]
yeah definitely :+1: 
I my have to do some code refactoring once I'm done with my current work ...

**Comment by funilrys** [comment]
I can't figure out how did you do for 1,6M =+> 2min  :rofl: @mitchellkrogza

**Comment by mitchellkrogza** [comment]
Not running a funceble test on https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist just generating a hosts file. Now up to 2,154,280 and generated in 3 min 26 secs. 👍

**Comment by funilrys** [comment]
Aw my bad I was thinking that you have Quantic computer :rofl: :rofl:

**Comment by mitchellkrogza** [comment]
🤣  no wish I did ..... amazing though what simple bash can achieve with a list that big. Gotta love bash even when I have morning like this morning when I end up BASH-ing my head against the wall with stupid mistakes.

**Comment by xxcriticxx** [comment]
looks like emoji movie over here

**Comment by funilrys** [comment]
Could we produce a movie @mitchellkrogza ? :rofl:

**Comment by mitchellkrogza** [comment]
LOL @xxcriticxx  sometimes we gotta have ourselves some fun with emoji's ...... helps ease the burden of when we are banging our heads against the wall writing code 🤣

**Comment by xxcriticxx** [comment]
@funilrys youtube how to be nice :)

**Comment by funilrys** [comment]
So true @mitchellkrogza :laughing: 

If he knew the mistake you made this morning he would laugh with us :rofl: :rofl: :rofl:

**Comment by xxcriticxx** [comment]
for sure time to work be back later emoji out

**Comment by funilrys** [comment]
Closing.
