### ISSUE TITLE
IP detected as INVALID

### ISSUE THREAD

**Issue by funilrys** [funilrys/funceble#83]
[The-Big-List-of-Hacked-Malware-Web-Sites](https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites) of @mitchellkrogza started to have `INVALID` output for IP.

This is produced by funceble and so after the introduction of IP adresses into its [domain.txt](https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/blob/master/.dev-tools/_strip_domains/domains.txt).

Time to integrate IP a bit better than now !!

**Comment by mitchellkrogza** [comment]
Ah I gotya now, failing on IP lookups. Certainly something funceble will
have to try and do in a  future release, shouldn't be a major hassles to
implement that though

**Comment by funilrys** [comment]
This is what is coming soon :+1: 
![screenshot from 2017-07-25 20-57-19](https://user-images.githubusercontent.com/14127285/28589002-96e037a2-717c-11e7-96d9-ba875d1197ec.png)

**Comment by funilrys** [comment]
To explain the unknown, if i don't set a timeout for the command which get the http code, the script take too much time ...

**Comment by xxcriticxx** [comment]
whats code 000?

**Comment by mitchellkrogza** [comment]
@xxcriticxx @funilrys been wondering that myself so I tested it.

`curl -I https://007angels.com
curl: (7) Failed to connect to 007angels.com port 443: Connection refused`

`curl -I http://007angels.com
curl: (52) Empty reply from server`

```
curl http://007angels.com
<html>
<head>
<meta name="robots" content="noarchive" />
<meta name="googlebot" content="nosnippet" />
</head>
<body>
<div align=center>
<h3>Error. Page cannot be displayed. Please contact your service provider for more details.  (16)</h3>
</div>
</body>
</html>
```

But if you visit 007angels.com in a browser it redirects you to ww5.007angels.com

So they are doing something on their Nginx server to prevent people digging for server information ???

**Comment by funilrys** [comment]
I can confirm that with my dev version of funceble and there are many cases like that ...

There are several hypotheses.
1. We are considered as bot
2. They blocked all nonbrowser call 
3. The domain name is for sale but is still connected to a server
4. They drop all connection to a specific port
5. ... let's complete this list :joy_cat: 

![screenshot from 2017-07-26 11-16-23](https://user-images.githubusercontent.com/14127285/28613842-e3f116d4-71f3-11e7-9475-8c08e40083ea.png)

**Comment by funilrys** [comment]
To complete the list ...
https://stackoverflow.com/a/9391270/5308363

**Comment by mitchellkrogza** [comment]
Very interesting

**Comment by mitchellkrogza** [comment]
Latest funceble working 100% detecting IP's now. See - https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites 👍  well done @funilrys funceble just keeps getting better and better. 💯

**Comment by funilrys** [comment]
Thanks @mitchellkrogza :+1: :smile_cat: The version dev-1.4.0+xxx is even better :wink: 

Gonna take a look at that later :+1:

**Comment by mitchellkrogza** [comment]
Awesome @funilrys looking forward to seeing it when you done with your changes.

**Comment by funilrys** [comment]
![default](https://user-images.githubusercontent.com/14127285/29406816-8798f126-8342-11e7-9361-89b8c5e20728.png)

**Comment by funilrys** [comment]
Thanks @mitchellkrogza :smile: 

![yeah](https://user-images.githubusercontent.com/14127285/29407219-f95b947a-8343-11e7-84ee-0b6f439b606b.png)

**Comment by mitchellkrogza** [comment]
Pulling now to my Ubuntu box and going to run it against those plaint text lists I created.

**Comment by funilrys** [comment]
switch to dev branch before :wink: 

I always leave the (upstream not local) dev branch as useable so that it's easier to get feedback about what I'm developing for the next release :smile_cat:
