### ISSUE TITLE
months 

### ISSUE THREAD

**Issue by xxcriticxx** [funilrys/funceble#84]
why are all months in lower case?

can you change to number format? for example 01-10-2017 or 01-10-17

**Comment by funilrys** [comment]
Because I designed it like it @xxcriticxx and I do prefer to have a month in English.

Can the format be changed ? Not for now but it can be a feature in a future release:+1:

**Comment by xxcriticxx** [comment]
it could be as option in setup to change from English months to numbers or something no rush just nice to have
