### ISSUE TITLE
Folder are not automatically created

### ISSUE THREAD

**Issue by funilrys** [funilrys/funceble#89]
As @mitchellkrogza highlighted into #71:

We should automatically create the directories. 
Indeed it'll be useful for further update and usages.

**Comment by mitchellkrogza** [comment]
I agree 💯  % 👍

**Comment by funilrys** [comment]
Fixed with https://github.com/funilrys/funceble/commit/01e6aa2abdf2cc924aa19979c1df2aa65eccca8c.

**Want to test/use the fix or give feedback about it before the next release?**
Simply clone or download 
 https://github.com/funilrys/funceble/tree/4f16347af4fe9c62999bb401bd5973421ebc04e2

P.S: Please **DO NOT** close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/funceble/commit/01e6aa2abdf2cc924aa19979c1df2aa65eccca8c will be merged to [`master`](https://github.com/funilrys/funceble/tree/master).
