### ISSUE TITLE
Auto(-save &) continue mode

### ISSUE THREAD

**Issue by funilrys** [funilrys/funceble#90]
Time to track this one :smile_cat: 

So because:
- travis have a limitation of 50 minutes
- @mitchellkrogza have a huge [Ultimate Hosts/Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) he want to test
- ..... Keep completing this list until this issue is fixed (Let's have some fun :wink: :joy_cat: )

It'll be great to add an auto (save &) continue  mode!

**Comment by xxcriticxx** [comment]
break up list in few pieces and run multiple terminals?

**Comment by funilrys** [comment]
No @xxcriticxx 😜 I already started you gonna see it in the dev branch in few hour I'm gonna sleep 🙂
