### ISSUE TITLE
Too short -t (timeout) can lead to false positives.

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/funceble#92]
@funilrys see - https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/commit/e0a15f6d6b9210da4c9de71ed9965a2b3e8e4652

**Comment by mitchellkrogza** [comment]
@funilrys I am not 100% convinced timeout is the cause of this. I think some registries are limiting lookups so on one run I get a positive hit "active" and then then later in the day on same domain I get a negative hit "inactive". I think, not sure of how you've coded this though, that if there is any failure on a whois lookup the nslookup result should be the winner.

**Comment by funilrys** [comment]
Yes but if we don't pass whois, nslookup is still there to tell us the status

**Comment by mitchellkrogza** [comment]
👍  ok gotya. Actually this just proves how accurate funceble is and how my brain was not working (lazy) to test why I got one INACTIVE after it was previously ACTIVE. 

That's because the site `http://matchgallery.homeandgardeningarticles.co.uk/6514626a35adfb3fa6f1d3f3c0a10fcf/login.php` has been pulled offline 👍  so ...... funceble RULES !!!!

**Comment by funilrys** [comment]
So this is not an issue anymore :smile_cat: 

Closing.

**Comment by mitchellkrogza** [comment]
100% ..... funceble is doing exactly what it was designed to do .... find dead domains and boy oh boy you have done some amazing work on this.
