### ISSUE TITLE
[Dev] FEATURE: Additional directories for plain list of domains.

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/funceble#93]
Suggest adding to `dir-structure`

```
output/domains
output/domains/ACTIVE
output/domains/INVALID
output/domains/INACTIVE
```

and having a switch to generate simple plain text file of domains in each directory with no commenting of any sort in the file.

**Comment by funilrys** [comment]
Done :smile_cat: 

As usually, do not close this manually :+1:

**Comment by mitchellkrogza** [comment]
Awesome, pulling fresh copy of dev branch now and going to run it against the new clean list from Badd-Boyz-Hosts. Any news on why percentage.txt was not created ?

Sorry me being stupid ..... I should not have added the -p switch .... duhhhh !!!

**Comment by funilrys** [comment]
Forgot the argument so moving this to in progress
